candid82/joker

core/data/linter_cljs.joke

Adds a linter exception for this-as, a ClojureScript macro that lets you bind JavaScript 'this' to a local variable.

linter: Adding missing ClojureScript this-as macro

---

README.md

couple of typo's in the linter output format description in the README

fix linter description in README

---

README.md

I've added instructions for installing Joker when using [Nix](https://nixos.org/nix/). Hope the wording sounds ok.
Version 0.8.6 is currently provided in nixpkgs and I've already submitted a PR to bump it to version 0.8.7.

Add nix installation to readme

---

core/data/linter_cljs.joke

Starting with 0.9.5 an exception is thrown when linting a cljs file that uses `:include-macros` in its `:require` form.
`bar.cljs:2:31: Exception: Unsupported option(s) supplied: :include-macros`
from https://clojurescript.org/guides/ns-forms#_sugar
> Similarly, there is `:include-macros` sugar that you can use to signal that the macros namespace should be required using the same specifications as the runtime namespace. So for example, this works:
> ```clj
> (ns bar.core
>  (:require [foo.core :as foo :include-macros true]))
>
> (foo/add 2 3)
> (foo/subtract 7 4)
> ```
This PR adds `:include-macros` to the list of allowed options.

fix :include-macros

---

README.md
main.go

The documentation could be expanded and clarified further, but this is a quick PR to add support so a release could be made and downstream clients encouraged to switch over to using `-`.

Support '-' (single hyphen) as alias for stdin

---

core/procs.go
main.go

Fixes: https://github.com/candid82/joker/issues/109
Note that this leaves `main.go` in a bit of a dodgy state in terms of code cleanliness, because `EVAL` not only means different things (as it did before), but there's a shiny new `Phase` value, `PRINT_IF_NOT_NIL`, that has a new meaning, but in only one context.
I'm up for cleaning that up, but wanted to keep this PR scoped to just fixing the issue at hand.

Print result of evaluating -e <expr> if not nil

---

tests/run-flag-tests.joke

One is "fake" and wouldn't work anyway because of limitations in how
the `testing` function parses string args. I'm leaving it in for now
in case I get time to try adding support for a test passing a vector
of args instead of a string, or some other simple solution.

Add tests of the --eval flag

---

main.go
tests/run-flag-tests.joke

These helped me see more clearly what was going wrong with the "fake"
test I'd added to tests/run-flag-tests.joke.

Support (undocumented) --debug=stdout and --debug=stderr options

---

core/procs.go

This is not the elegant solution for which we were hoping, but it seems to work well, the key being to ensure the underlying `io.Reader` object, whatever its concrete implementation, is maintained such that a `(read-line)` reads only as far as necessary ("unreading" as appropriate) so the next `(read-line)` (or `(read)`) call works properly.
Fixes: https://github.com/candid82/joker/issues/129

Fix (read-line) so it works inside (with-in-str ...)

---

go.mod
go.sum

This adds Go module support (for Go >=1.11). 
This makes it cleaner to build `joker` in package managers because we can omit setting up `GOPATH` and can build directly in the directory.

Add module

---

core/environment.go
core/gen/gen_types.go
core/types_assert_gen.go
core/types_info_gen.go
docs/joker.string.html
main.go
std/arity.tmpl
std/base64/a_base64.go
std/fn.tmpl
std/html/a_html.go
std/http/a_http.go
std/intern.tmpl
std/json/a_json.go
std/math/a_math.go
std/os/a_os.go
std/os/os_native.go
std/package.tmpl
std/string/a_string.go
std/time/a_time.go
std/url/a_url.go
std/yaml/a_yaml.go

Apply 'go fmt' Style

---

.circleci/config.yml
eval-tests.sh
tests/eval/read-line/input.joke
tests/eval/read-line/lines.txt
tests/eval/read-line/stdout.txt
tests/run-eval-tests.joke

Pretty much just `linter-tests.sh` and friends, modified to support testing of fairly arbitrary input files (named `input.joke`) that are evaluated.
An `input.joke` file should be able to easily shell out and run `joker` on some other file in the same directory, as it is run in the test directory and can look at the first element of `(joker.os/args)` to find the name of the executable.
This is crude but promises to be effective as a start.

New script to test evaluation of forms from input files

---

core/data/core.joke
std/generate-std.joke

`joker.math/pi` works in the current version, but this fix allows one to `(require '[joker.math :as m])` and such. Ditto the other libs added.
(Also sorted the libs so it's easier to see what's missing.)

Fix e.g. (use 'joker.math)

---

std/generate-std.joke

The indentation changed in places where `joker.string` was replaced with `s`.

Cleanup indentation and code

---

.gitattributes
docs/joker.core.html

I'm not 100% sure this is the right approach. It'll prevent editing of (most) Joker source files via NotePad on Windows (since NotePad doesn't handle Unix-style line terminators correctly). I'm not sure whether there'll be other issues.
But it avoids requiring tools like `run-eval-tests.joke` to "manually" strip out carriage returns in expected outputs (they don't seem to show up in generated output, at least not in Git Bash) before comparing them.
Since I don't currently have a non-Git-Bash, barebones Joker development environment on a Windows machine, it's hard to predict what effect this might have on such environments; but they're currently probably rather broken anyway due to lack of a `run.bat` and other equivalents for shell scripts.
While doing this work (which was rather painful, …

Fix Test Comparisons on Windows

---

core/data/test.joke
tests/eval/control.joke
tests/test-helper.joke
tests/test_helper.joke

This exposed a bug in `joker.test`, also fixed herein.
I'm not sure `test_helper.joke` is in the right place. The way `require` currently works (with respect to the multilevel namespaces, as in `*ns*`, used by this test infrastructure) complicated my attempts to do something a little more elegant. For now, it seems to work.

Port clojure.test-clojure.control

---

tests/eval/control.joke
tests/test-helper.joke

Somehow missed seeing this earlier...yet they show up as red boxes on my Mac laptop, so they should have been obvious (guess I didn't `git diff` the full PR itself before submitting).

Delete trailing whitespace

---

core/data/linter_clj.joke

The following don't need to be imported and hence shouldn't fail linting.
- java.lang.BigInteger
- java.lang.Thread$State
- java.lang.Thread$UncaughtExceptionHandler

Add a few more java.lang classes to the linter

---

core/procs.go

Thanks for joker, I've found it extremely useful!
I was writing a script that has some regex parsing in it and noticed that `re-seq` and `re-find` behave a little differently than in clojure (aside from re-seq not being lazy, which isn't a big deal). This PR includes a couple of changes to bring these functions more in line with their clojure cousins:
1. `re-seq` returns `nil` instead of an empty sequence when there are no matches:
```clj
#_=> (re-seq #"nothing-should-match" "test-string")
nil
;; Currently this returns ()
```
2. Regex matching functions return `nil` instead of `""` when a group does not match. This is consistent with how [java.util.regex.Matcher.group()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Matcher.html#group(int)) works:
>  If the …

Make re-seq and re-find return nil when appropriate

---

core/procs.go
core/stringable.go
std/string.joke
std/string/a_string.go

Clojure isn't entirely consistent with this, but it is common to allow passing a char as a secondary argument in functions that operate on strings (e.g. `join`, `replace`, `index-of`).
Adding a `Stringable` pseudo-type seemed like the most straightforward way to accomplish this, but it does feel a little awkward, since all the other types have generated `Ensure` and `Assert` functions. I'd be open to doing this another way if you'd prefer.

Allow passing char to some joker.string functions

---

main.go

The tests in #186 failed, but circleci reports that they passed, because joker exits 0 in all cases when evaluating code. I'm not sure 1 is the correct exit code (since there are a lot of exit codes in main.go), but I don't think it should be 0.
Specifically, the [eval tests](https://circleci.com/gh/candid82/joker/599) failed since I forgot to push the `gen_data.go` file in that PR.

exit 1 when eval errors

---

core/array_map.go
core/eval.go
core/read.go
main.go

Fixes https://github.com/candid82/joker/issues/200 with only slight modifications to the proposed changes (to ensure the command-line value is parsed as an `int64` in the first place).
Tested via:
```
$ GOOS=linux GOARCH=386 go build
$ file joker
joker: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, not stripped
$ ./joker
Welcome to joker v0.12.2. Use EOF (Ctrl-D) or SIGINT (Ctrl-C) to exit.
user=> ^D
$ ./all-tests.sh
[...]
Ran 59 tests containing 511 assertions.
0 failures, 0 errors.
All three tests passed.
$
```

Fix builds for 32-bit hosts

---

shadow.sh

This provides the shadowed-variable checking that `run.sh` used to do, but no longer does, keeping that script simple.
This new script supports Go 1.12 as well as previous releases; 1.12 support requires installation of the `shadow` tool to work (see the diagnostic produced for more info).
If this script is found sufficiently worthy, I suppose it could be invoked by `run.sh` in the `build()` function. In the meantime, it's available for developers changing Joker code.

Create shadow.sh script

---

std/time.joke
std/time/a_time.go

A couple extra functions in the joker.time namespace. I didn't get this far, but it would open up the possibility of adding an `#inst` data reader in the future.

Add joker.time/parse and add-date

---

README.md

mention `(in-ns 'joker.core)` and link to #50

change the README regarding `linter.clj[c|s]` files

---

eval-tests.sh
std/os/os_native.go
tests/eval/os.joke
tests/eval/stdin-pipe/input.joke
tests/eval/stdin-pipe/stdin.txt
tests/eval/stdin-pipe/stdout.txt
tests/run-eval-tests.joke

I was trying to do something like
```clojure
(defn get-pass [prompt]
(try
(stty "-echo")
(get-input prompt)
(finally
(stty "echo")
(println))))
```
and couldn't because the `:stdin :pipe` wasn't really a terminal.
I added tests for string and :pipe and then made the change to pass the object directly and added some tests for that, though it will only work when there really is a tty.
If you agree with the concept I have some design questions for you:
- do you see any reason to keep the previous :pipe behavior? I believe this works the same, but it could be a different keyword if there was any distinction.
- i added 3 different tests for the tty behavior, all of which are a little weird.  do you prefer one over the others (or have another suggestion)?
I appreciate your feedback.  Joker is …

Pass actual Stdin object to os.exec commands

---

std/os/os_native.go

Fix https://github.com/candid82/joker/issues/237 by simply using the built-in `cmd.Stdout` and `cmd.Stderr` fields to hold buffers that will be written to (asynchronously) such that `cmd.Wait()` knows to wait for such writing to complete before tearing things down.

Fix stdin pipe so output reliably captured

---

core/object.go
std/time.joke
std/time/a_time.go

Possible fix for https://github.com/candid82/joker/issues/243.

Quick fix for 32-bit hosts

---

core/data/repl.joke

Also print cleaner diagnostic for (doc :any-keyword).
This enables e.g.:
```
user=> (doc joker.core)
-------------------------
joker.core
Core library of Joker.
nil
user=> (doc joker.math)
-------------------------
joker.math
Provides basic constants and mathematical functions.
nil
user=>
```

Support (doc <namespace>)

---

core/environment.go
core/ns.go
main.go
std/base64/a_base64.go
std/crypto/a_crypto.go
std/csv/a_csv.go
std/filepath/a_filepath.go
std/hex/a_hex.go
std/html/a_html.go
std/http/a_http.go
std/json/a_json.go
std/math/a_math.go
std/os/a_os.go
std/package.tmpl
std/strconv/a_strconv.go
std/string/a_string.go
std/time/a_time.go
std/url/a_url.go
std/yaml/a_yaml.go

This is something of a proof of concept, as it doesn't seem to speed up official Joker much that I can measure on the two machines I'm using while on vacation (and my main development machine, at home, is even less likely to show much of a difference).
But, applied to my `gostd` fork, the resulting Joker definitely starts up faster, though still not as quickly as official Joker. (I think there's room for further improvement, in terms of delaying `var`-time initialization until `Init()` is called. That might help things further.)
That suggests this PR, or something like it, could keep Joker startup times from getting much longer even if/as more namespaces and/or functions (vars) are added to its default library.
Note that, while trying different ideas out, I was disappointed to discover …

Try initializing namespaces lazily

---

std/base64/a_base64.go
std/crypto/a_crypto.go
std/csv/a_csv.go
std/filepath/a_filepath.go
std/fn.tmpl
std/generate-std.joke
std/hex/a_hex.go
std/html/a_html.go
std/http/a_http.go
std/json/a_json.go
std/math/a_math.go
std/os/a_os.go
std/package.tmpl
std/strconv/a_strconv.go
std/string/a_string.go
std/time/a_time.go
std/url/a_url.go
std/yaml/a_yaml.go

This defers most everything in the `std/` libraries.
The one remaining item (that I know of) is `client` in `std/http/http_native.go`, which the `gostd` fork defers using a general mechanism that could be ported over to here as well, if deemed worthwhile.

Merge more startup-time laziness/deferral from gostd fork

---

std/base64/a_base64.go
std/crypto/a_crypto.go
std/csv/a_csv.go
std/filepath/a_filepath.go
std/generate-std.joke
std/hex/a_hex.go
std/html/a_html.go
std/http/a_http.go
std/json/a_json.go
std/math/a_math.go
std/os/a_os.go
std/package.tmpl
std/strconv/a_strconv.go
std/string/a_string.go
std/time/a_time.go
std/url/a_url.go
std/yaml/a_yaml.go

This should have no effect on official Joker, but (besides being
correct and consistent with how the :doc tags are treated elsewhere)
it fixed the `gostd` fork when reading the generated online docs, on
my website, for `html/template`, which include this gem:
```
"<script>alert('you have been pwned')</script>"
```
(I was actually getting that alert whenever reloading that page!)

Quote namespace doc string

---

core/data/core.joke
core/data/repl.joke
core/object.go
core/procs.go

Not sure this is the best approach, but wanted to try it before working on adding (autogenerated) documentation of (Joker-wrapped) Go types in the `gostd` fork, to prevent the fork from straying further from the official version.
So, feedback highly welcome!
(Note that I added actual documentation to only the `Int` type, just to try it out.)

Support joker.repl/doc of types

---

core/data/core.joke
core/procs.go
docs/generate-docs.joke
docs/templates/index.html
docs/templates/type-summary.html
tests/eval/types.joke

Assuming https://github.com/candid82/joker/pull/268 is merged, this could then be merged to actually use the new function when generating docs.
(I don't have strong feelings about the stylistic changes I made to the `index.html` page to accommodate listing types; just wanted to get it working and look fairly reasonable without being too intrusive.)

Doc all types

---

core/data/walk.joke
docs/generate-docs.joke
std/http.joke
std/http/a_http.go

This should improve consistency and readability of the generated docs, and avoid issues when "special" character (in HTML) are in `:doc` strings.

Use first line only in namespace summaries, and HTML-escape :doc strings

---

run.sh

The current behavior is to silently fail, which is confusing (when it happens to us developers).
However, this approach relies on failures printing an unexpected diagnostic; merely exiting with a nonzero return code no longer suffices.
I'm not sure whether it's worth fixing that possibility, given that a better fix might be to inhibit the expected warnings (and blank lines) entirely, rely solely on the return code, and not /dev/null the output.

Show unexpected errors from the generate-std.joke step

---

core/data/core.joke

My `gostd` branch's `generate-docs.joke` documents constants, and crashed due to missing metadata on this (helpful!) new var.

Add doc and meta for *main-file*

---

core/array_map.go
std/addmeta.tmpl
std/generate-std.joke
std/intern.tmpl

This treats the `std/*.joke` more like the `core/data/*.joke` files in that "all" the metadata on each public symbol is provided during interning.
That being said, for now this PR doesn't really handle anything (for values of meta tags) other than strings and integers. Any other type is stringized.
While this is theoretically useful in canonical Joker, I found this helpful (for generating better documentation) in the `gostd` fork.

Add other meta tags

---

core/data/markup.joke
core/gen_data/gen_data.go
core/procs.go
docs/generate-docs.joke
docs/index.html
docs/joker.markup.html
tests/eval/markup.joke

Patterned on Hiccup, this namespace allows for rendering of XHTML (and variants) markup from vectors and strings.
It is not a direct port of Hiccup, as it is strictly interpretive, but its basic API is compatible with Hiccup (nearly all tests were just copied over unchanged), and should be quite sufficient for generating blog posts, XML configuration files, or other similar operations in Joker's intended domain.

Add joker.markup namespace

---

core/object.go

gen_data.go imports Joker's core, which requires that to compile cleanly.
But gen_types.go generates code that is built into Joker's core, while not depending upon it.
Therefore, the "go:generate" lines that run gen_types.go should come before the one that runs gen_data.go.
Test this by editing (say) core/types_assert_gen.go to make it uncompilable and rebuilding (via run.sh or similar).
The "go generate ./..." step should regenerate core/types_assert_gen.go, replacing the uncompilable version with a working version, before gen_data.go is then run and imports core.

Generate code for core before depending on it for further generation

---

std/os.joke
std/os/a_os.go

Per https://clojurians.slack.com/archives/C9VURUUNL/p1574457045102100, seems like these should be available without resorting to the `gostd` fork at this time.

Add joker.os/remove{,-all}

---

core/data/core.joke

Happened to notice this and can't see any reason for it to be missing!

Add joker.repl to *loaded-libs*

---

eval-tests.sh
tests/run-eval-tests.joke

This allows `./joker tests/run-eval-tests.joke` (run from a command line,
so stdin is a tty) to support tty-related testing.

Improve tty testing so it works outside of the eval-tests.sh script

---

tests/eval/deps.joke

Instead of guessing which argument, in the original invocation of Joker,
has the filename, or even using the Joker-provided `*command-line-args*`
variable, just use `*main-file*` directly (it's a new-ish feature).
This allows the test to pass even if Joker options (not options to the
Joker script being invoked) are provided. E.g. this works:
```
./joker --evaluate tests/run-eval-tests.joke
```

Fix deps.joke to use source filename directly

---

core/object.go
tests/linter/defmethod/output.txt
tests/linter/letfn/output.txt
tests/linter/macro-call-1/output.txt
tests/linter/macro-call/output.txt

This helped me out on one of my development branches.

Improve diagnostics around wrong-arity function calls

---

core/data/better_cond.joke
core/gen_data/gen_data.go
core/procs.go
tests/eval/better-cond-test.joke

This PR adds namespace `joker.better-cond`, based on code extracted from https://github.com/Engelberg/better-cond.
I've found that nearly every Joker script I've written has needed `cond-let` (a more limited version of better-cond's version of `cond`).
Original work licensed under Eclipse Public License.

Create joker.better-cond from Engleberg/better-cond

---

tests/run-eval-tests.joke

This fixes one issue, but there's a downstream failure involving `lib/test-local/lib.joke` and pathname separators running under Git Bash on Windows that should be fixed.
Note that I'm not entirely sure why I went with `/usr/bin/env` in the first place, below, other than it's canonical. Nor have I investigated why that approach yields this message (without this fix):
```
tests/run-eval-tests.joke:5:11: Eval error: exec: "/usr/bin/env": file does not exist
```
I hope this change doesn't break other OSes!

Exec 'test' directly, not via '/usr/bin/env'

---

std/string.joke
std/string/a_string.go
std/string/string_native.go
tests/eval/string.joke

This extends `split` beyond what `clojure.string/split` provides, makes `split` more consistent with other `joker.string` functions, and sets the stage for a straightforward fix to the Windows bug in `deps.joke`.
With this, https://github.com/candid82/joker/pull/319 is (for me) less urgent.

Support joker.string/split string separator

---

core/object.go
core/parse.go
core/procs.go
core/read.go
core/types_assert_gen.go
core/types_info_gen.go
std/string/string_native.go

This allows `gen_code.go` (currently on the `gen-code` branch of my fork of Joker) to easily update, at lazy-initialization time, an `Object`'s `.Value` with the resulting of a `regex.MustCompile()` call.

Make Regex a reference type

---

run.sh

Various changes made in the `gen-code` branch not only produce additional `a_*code.go` files, but change the way `a_*data.go` files are generated.
So it's best to start with a clean slate before running `go generate ./...`, to prevent it picking up those stale files.
Another approach to this could be to use build tags so `go generate`-run tools don't pick up any `a_*.go` files at all, but this seems easier and more effective.

Avoid breaking developer builds during gen-code integration

---

core/data/core.joke
core/environment.go
core/ns.go
core/procs.go
main.go

This is not strictly necessary, but I found it invaluable, mainly when adding tests for verbosity levels greater than 1 (the default for one specification of `--verbose`) that would use `go-spew` to output substantial data sets.

Bring verbosity improvements over from gen-code branch

---

core/environment.go
core/parse.go
core/procs.go
main.go

This is a precursor to separating out the initialization code into a distinct source file, `environment_init.go`, that (like the other `*_init.go` files that will be split off) is built only when `!fast_init` (which is true when building the normal version of Joker).
The fast-startup version of Joker is built with `-tags fast_init`, so those `*_init.go` files will not be compiled in, but their effects will be in the form of `core/a_*code.go` files generated by `gen_code.go` (forthcoming).
(It seemed like a good idea to make this a separate PR from the PR to actually split out the files, which will make it hard to detect changes in the text of the code that is split out. The idea here is to have no such changes to that code, just the source-file splits, in a subsequent PR.)

Separate environment.go init code from decl code

---

core/object.go
core/procs.go
core/spew_disabled.go
core/spew_enabled.go
std/base64/a_base64.go
std/crypto/a_crypto.go
std/csv/a_csv.go
std/csv/csv_native.go
std/filepath/a_filepath.go
std/fn.tmpl
std/generate-std.joke
std/hex/a_hex.go
std/html/a_html.go
std/http/a_http.go
std/io/a_io.go
std/json/a_json.go
std/math/a_math.go
std/os/a_os.go
std/package.tmpl
std/strconv/a_strconv.go
std/string/a_string.go
std/time/a_time.go
std/url/a_url.go
std/yaml/a_yaml.go
tests/eval/csv.joke

Needed by the `gen-code` branch (on my fork) to generate static Go code that instantiates a `Proc` given one that it finds while traversing Joker's data structures.
Also makes this work:
```
$ ./joker
Welcome to joker v0.14.1. Use EOF (Ctrl-D) or SIGINT (Ctrl-C) to exit.
user=> cons
#object[Proc:procCons]
user=> joker.string/blank?
#object[Proc:std/string.isblank_]
user=>
```
Previously, only `#object[Proc]` would be output, providing no information on which `Proc` was stringized.
(Note that the individual commit messages are missing the `#object` lines, presumably because they were treated as comment lines!)

Make Proc's self-identify

---

core/environment_init.go
core/gen_data/gen_data.go
main.go

This isn't needed for the fast version (forthcoming `gen-code` branch), nor by `gen_data.go` that I can see.

Refer core namespace to user namespace only when building slow version

---

run.sh

Recent changes to how these files are generated do not consistently conform to Go coding conventions.
Rather than try to keep up with those via changes to `generate-std.joke` and its `*.tmpl` files, just run `go fmt ./...` on the `std/` directory after generating those files.
That way, mere formatting differences won't force rebuilding Joker.

Run go fmt on generated std/ files

---

core/procs.go

Fixes crash on this when in a "short" path such as `/tmp`:
```
(ns foo.barfizz.buzz.core (:require [clojure.string :as str]))
```
Fixes: https://github.com/candid82/joker/issues/357

Fix panic when exhausting pathname components for namespace

---

DEVELOPER.md
README.md
run.sh

The next step towards https://github.com/candid82/joker/issues/362, this causes `run.sh` to (in the default case) no longer build a `joker.slow` executable. Or, an env var or flag file can be used to build that but not `joker.fast`.
`go build -tags slow_init` and such can still be used afterwards to build such an executable (as `joker`), so A/B testing is still supported. That is, all the relevant `*_data.go`, `*_code.go`, `*_slow_init.go`, and `*_fast_init.go` files are still generated.
Documentation updated accordingly, including fixing/clarifying a few things that predate this PR.

Build only one executable via run.sh

---

core/data/core.joke
std/bolt.joke

Needs a test of some sort, which would have caught this.
(Also, would be great to automatically populate `*loaded-libs*` as is being done for `*core-namespaces*`.)

Get joker.bolt working

---

core/data/core.joke

Note the missing info in current Joker versus with this change:
```
$ joker -e '(joker.repl/doc *file*)'
-------------------------
The path of the file being evaluated, as a String.
When there is no file, e.g. in the REPL, the value is not defined.
$ ./joker -e '(joker.repl/doc *file*)'
-------------------------
joker.core/*file*
The path of the file being evaluated, as a String.
When there is no file, e.g. in the REPL, the value is not defined.
```

Add :ns and :name to metadata via add-doc-and-meta

---

tests/eval/bolt.joke

Close file ASAP (and nil out the var for it) while avoiding race conditions.
Before closing the file, capture its name, then use that when opening the db and, later, removing the file.
Tested on Windows (and Ubuntu).

Better bolt test fix

---

.gitignore
docs/dash.sh

Somehow I missed that the original approach wasn't working due to being run in `docs/dash/` instead of `docs/`.

Fix joker.xml generation

---

exiters.go
exiters_plan9.go
exiters_windows.go
go.mod
repl.go
repl_plan9.go

As Joker doesn't seem to need any changes to support Ctrl-Z (or Ctrl-\) properly, either in the REPL or when calling `(joker.core/read-line)` from it, these changes seem to be all that's left to be done, and they have no important dependency on any particular version of `liner`.

Improve REPL Welcome Message

---

DEVELOPER.md

New Joker fan here! Been having a great time migrating all my old bash junk to joker this week 😍 
The current links out of DEVELOPER to LIBRARIES and README 404 when reading the developer instructions from GitHub.
The new ones use relative links instead of absolute links; they now resolves to the actual hosted page at e.g. https://github.com/candid82/joker/blob/master/LIBRARIES.md and should also work within branches if browsing non-`master` branches.

Fix broken doc links in DEVELOPER.md

---

core/object.go

My most-recent PR missed changing this one, so broke the diagnostic.

Fix (compare true 2) diagnostic message

---

core/gen/gen_types.go
core/object.go
core/procs.go
core/stringable.go
core/types_assert_gen.go
std/bolt/bolt_native.go

This moves more of the repetitive code into a couple of new functions.
As a compiler writer, I'd expect the resulting binaries to be smaller; but they seem to get a tiny bit larger with this changeset. I'm not sure why, unless Go is somehow better at consolidating repeating code, when it's beyond a certain size or complexity, than writing (generating) less of it in the first place, when it might be not bothering?
But I think the results are easier to look at and understand, and (if merged) I think it puts my next chunk of `gostd` work in a better position, as that needs another "dimension" (or perhaps several) of ways to extract objects.

Further simplify ensurers

---

core/object.go
tests/eval/printer.joke

Fixes https://github.com/candid82/joker/issues/434.
Note that Go's "%g" format specifier always outputs exactly three non-whitespace runes after the "e" (for exponent), besides other differences to Clojure/JVM, such as using "e" instead of "E", and not ensuring the string preceding "e"/"E" has a decimal point and at least one trailing digit.
So `1e-7` renders as "1e-07", for example. (Clojure 1.10.1 renders this "1.0E-7".)
ClojureScript's output looks more like what Joker would with this PR applied, except it renders `1e-7` (or any numerical equivalent) as "1e-7", omitting the unnecessary leading 0. (It also renders values that can be precisely converted to integers as integers; this PR avoids doing that via some extra code, which I think is necessary to avoid bugs such as when formatting …

Fix float output

---

core/procs.go
tests/eval/format.joke

This helps `(format ...)` produce useful results for format specifiers other than `%s`, such as `%x`, `%f`, and `%g`, when the operands don't fit into Native Joker types but can be accurately represented as native Go types.
The toNative() function is renamed so it's exported and thus usable by other libraries in the future.

Better native conversion for (format ...)

---

core/numbers.go
core/object.go
core/procs.go
core/read.go

The docs for big.Float, big.Int, and big.Rat specify that objects of those types shouldn't be copied (except via the appropriate `.Set()` method), but rather that pointers to them be used:
> shallow copies of <type>s are not supported and may lead to errors
It seems best (and fairly straightforward) to conform to those requirements.

Use math/big Package Properly

---

core/procs.go
tests/linter/macro-call/input.clj
tests/linter/macro-call/output.txt
tests/linter/ns-4/output.txt
tests/linter/ns-6/output.txt
tests/linter/ns-8/output.txt

The first commit herein, changing the `macro-call` linter test, illustrates what seems to be an inconsistency with regard to whether linting (or, more generally, parsing without evaluation) continues after an error.
This PR tries to clean up some such inconsistencies, but it's not 100% clear to me this is The Right Thing To Do. Still, it might be what people reasonably expect when linting (e.g. that a malformed macro invocation doesn't shut down further linting).
A potential problem with this is "runaway errors", such as when an early parsing error causes a deluge of downstream errors for code that's just fine once that early error is fixed.
The Go compiler mitigates such situations with a "too many errors" diagnostic after some number of errors. That might be worth considering, and I'm …

Keep on Linting After Parse Errors

---

core/procs.go

today, if you write `(read (os/open f))` then Joker will crash telling you that it expected a RuneReader but that you gave it a File
so this PR implements a very small change to `read` that will wrap `io.Reader` (which File implements) in bufio.NewReader (which implements RuneReader)

have read__ wrap io.Reader

---

std/json.joke
std/json/a_json.go
std/json/a_json_slow_init.go
std/json/json_native.go

Make the `json-seq` function accept the `keywords?` option for symmetry with `read-string`.

json-seq: add the keywords option

---

tests/eval/large-forked-stdout/input.joke
tests/run-eval-tests.joke

Fixes https://github.com/candid82/joker/issues/479 by not relying on `$PWD` being set as previously expected (before Go 1.19), which wasn't quite correct anyway, across a fork/exec.

Pass path to Joke executable as arg to eval/*/input.joke

---

docs/joker.markdown.html
std/markdown.joke
std/markdown/a_markdown.go
std/markdown/a_markdown_slow_init.go
std/markdown/markdown_native.go
tests/eval/markdown.joke

I've been building a little static site generator with joker and was missing the ability to turn off the hard line wraps. I've added flags for the other rendering options just for good measure.
I hope the style is ok. I'm not sure what the right pattern is for throwing an exception from the native Go code when a type is wrong. If there is a nicer way I'll happily update it. 
Thanks!

Add control over markdown rendering options

---

core/gen_code/gen_code.go

Create `a_data.go` in a reproducible way.
We sort to counter golang's random map iteration order.
Note that there is another issue left in the generation of `a_linter_all_data.go`.
This PR was done while working on [reproducible builds for openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds).

Create a_data.go in a reproducible way

---

core/data/linter_clj.joke
core/data/linter_cljx.joke

Similar to: https://github.com/candid82/joker/issues/489
and: https://github.com/candid82/joker/commit/1d154363b529976a0aeec74cededf6147f218fe5
```
harold@freeside:~$ cat test.cljs 
(ns test)
(abs -1)
harold@freeside:~$ joker --version
v1.3.1
harold@freeside:~$ joker --lint test.cljs 
test.cljs:3:2: Parse error: Unable to resolve symbol: abs
```
Not sure if this is the correct fix, but wanted to show respect for your time - still loving `joker` as my clojure(script) linter and refactoring assist tool, we fly because of this software.
Thank you!

`[linter]` add abs to cljs

---

std/time.joke
std/time/a_time.go
std/time/a_time_slow_init.go

A simple function in Go time’s package – but useful if you are using a “year-day” format in your script (e.g. I commonly use format like `2023_344.backup` for timestamp on files).
I did not see tests specific to the time package, but running the script manually looking ok:
```
user=> (joker.time/day-of-year (joker.time/now))
359
```

Add day of year to joker.time
