README.md
add ale to the list of linters for vim
=> add ale linter to README

README.md
=> add link to vscode extension

main.go
Per https://github.com/candid82/joker/pull/79#issuecomment-420516049.
=> Warn if '--' is used for a filename

run.sh
This now works:
```
./run.sh -e '(println "i am here")'
```
=> Fix run.sh script

std/http/http_native.go
Fixes: https://github.com/candid82/joker/issues/94
=> Fix build error due to shadowed variable

.gitignore, docs/index.html, docs/joker.core.html, docs/joker.os.html, std/os.joke, std/os/a_os.go, std/os/os_native.go
This fixes:
https://github.com/candid82/joker/issues/99
However, it also updates re-generated files, which I'm not sure is properly included in this PR.
Please advise.
=> Also return integer exit code from joker.os/sh (and sh-from)

.gitignore
Ran into this testing on Windows (where Joker "kinda" works...).
=> Exclude .EXE files

main.go
This is for consistency with Clojure and Lumo.
Fixes: https://github.com/candid82/joker/issues/110
=> Rename the --expr option to --eval

README.md, main.go
Fixes https://github.com/candid82/joker/issues/77.
(Seems like enough time, and at least one release, have passed since this was deprecated.)
=> Change "--" to mean only end of Joker options, never stdin

core/environment.go
Addresses: https://github.com/candid82/joker/pull/124#discussion_r234872502
=> Incorporate PR feedback

core/data/core.joke, core/procs.go
Fixes: https://github.com/candid82/joker/issues/126
=> Fix (read-line) to read entire lines

core/object.go, std/os.joke, std/os/a_os.go, std/os/os_native.go
(Not sure that `MakeError()` is quite right for the long term.)
=> Support joker.os/chdir

std/base64/a_base64.go, std/fn.tmpl, std/generate-std.joke, std/html/a_html.go, std/http/a_http.go, std/intern.tmpl, std/json/a_json.go, std/math/a_math.go, std/os/a_os.go, std/package.tmpl, std/string/a_string.go, std/time/a_time.go, std/url/a_url.go, std/yaml/a_yaml.go
Scratching another itch here, as I move `gostd2joker` into the Joker source tree and continue work on it, and want to ensure my (Go) code is properly formatted without hassle....
=>  Produce more-gofmt-compatible output

std/generate-std.joke
...should have done all these earlier...
=> Use 's' abbrev for 'joker.string' everywhere

README.md
There're probably more suggestions that could be added, but this is a modest start.
=> Add a tiny section with some advice from PR feedback

docs/joker.string.html, std/string.joke, std/string/a_string.go
Same as trim-left and trim-right, but these are the clojure names
=> Add joker.string triml and trimr

all-tests.sh
=> Save Invoking Three Test Scripts By Hand

core/data/repl.joke
These were easy to do. The source functions need further thought.
Partially addresses: https://github.com/candid82/joker/issues/196
=> Add dir and apropos functions

main.go, tests/run-flag-tests.joke
Fixes: https://github.com/candid82/joker/issues/203
=> Allow negative numbers as arguments

core/data/core.joke, main.go
Resurrecting my old PR. I'm not sure it's current (with respect to how it changes the docs).
@candid82 -- let me know if you want me to properly update this, add tests, etc.
=> Add JOKER_CLASSPATH env var back

core/data/core.joke, core/deps.go, core/procs.go, tests/eval/deps-test.joke
This new dependency-management system looks great!
While looking through the PR, I found a few minor issues. This should fix those.
Thanks!
=> Minor fixes & cleanups

core/object.go, core/parse.go, tests/linter/condp/output.txt
Fixes: https://github.com/candid82/joker/issues/219
=> Sort warnings about unused parameters and bindings by symbol name

core/data/core.joke, core/procs.go, tests/eval/types.joke
Alternate (simpler) approach to addressing https://github.com/candid82/joker/issues/267 per discussion.
=> Add joker.core/types__ as private function

main.go
This is very handy for retrying (possibly with editing), in the dropped-into-repl, previous lines from a `--file` (or even `--expr`).
E.g. after `joker --exit-to-repl --file <somefile>.joke` and finding oneself in the repl, at which point `<somefile>.joke` will have been read, an up-arrow will (via `readline`) bring up the most recent line read from `<somefile>.joke`, as the history of those reads will have been saved.
Shouldn't cost anything (measurable) unless `--*-to-repl` has been specified (and of course `--file`/`--expr` is in effect).
Note that the extra "logic" (of initializing the new var to `true` and including it in the conditional) is currently unnecessary, but allows dropping in another option to disable just this one feature, if one wishes. I don't know why anybody would …
=> Save --file/--expr input for history playback when --*-to-repl in effect

std/math.joke, std/math/a_math.go, std/math/math_native.go, tests/eval/math.joke
Might do more later, but had some downtime and decided these might be useful for now.
=> Add more constants and functions from Go math package

core/line_runereader.go, main.go, repl.go, repl_plan9.go, std/os/os_native.go, std/os/sh.go, std/os/sh_plan9.go
Some function modifications to allow joker to be built for plan9.
=> Plan9 support

DEVELOPER.md, LIBRARIES.md, README.md, core/data/core.joke, docs/misc/lib-loader.md
First cut. See "Limitations" at the end of `LIBRARIES.md`.
=> Improve docs, especially re library loading/organization

docs/generate-docs.joke
When I merged master into my gostd branch, my recent change (to master's generate-docs.joke) looked really ugly, with its conditional definition of a top-level function.
This cleans that up, leaving the code a tad more Clojure-like.
=> Clean up the doc script a bit

tests/eval/macro-test.joke
Confirms: https://github.com/candid82/joker/issues/330
=> Confirm recent bugfix (avoid regressions)

core/data.go, core/procs.go
Put var decl in same file where it's used.
=> Minor code cleanup

DEVELOPER.md, core/data/core.joke, core/environment.go, core/environment_slow_init.go, std/base64/a_base64.go, std/bolt/a_bolt.go, std/bolt/a_bolt_slow_init.go, std/crypto/a_crypto.go, std/csv/a_csv.go, std/filepath/a_filepath.go, std/hex/a_hex.go, std/html/a_html.go, std/http/a_http.go, std/io/a_io.go, std/json/a_json.go, std/math/a_math.go, std/os/a_os.go, std/package.tmpl, std/strconv/a_strconv.go, std/string/a_string.go, std/time/a_time.go, std/url/a_url.go, std/uuid/a_uuid.go, std/yaml/a_yaml.go
One more thing to not have to remember to do when adding a lib to `std/`....
=> Automate populating *loaded-libs*

DEVELOPER.md
Fixed https://github.com/candid82/joker/issues/397.
=> Fix typo in command

core/procs.go, tests/eval/core.joke
Fixes https://github.com/candid82/joker/issues/410
=> Avoid crash on (meta) with wrong # of arguments

LIBRARIES.md, README.md, docs/misc/lib-loader.md
Thanks, @dpritchett, for lighting the way on this! These links will now also stay within the selected fork/branch when followed.
=> More relative urls

core/object.go, core/read.go, tests/eval/printer.joke, tests/eval/reader.joke
Fixes: https://github.com/candid82/joker/issues/423
=> Support ##Inf, ##-Inf, and ##NaN

core/read.go
Fixes https://github.com/candid82/joker/issues/436, though I'm not convinced this is intentional behavior in ClojureScript.
=> ClojureScript dialect: Treat leading .<digit> as number

std/string.joke, std/string/a_string_slow_init.go, std/string/string_native.go, tests/eval/string.joke
Fixes https://github.com/candid82/joker/issues/441.
=> Fix limit on splitting strings

core/read.go
Fixes https://github.com/candid82/joker/issues/447, except for the non-breaking-space exceptions described therein.
=> Allow Symbol/Keyword Lexemes a la Clojure

core/ns.go
Fixes https://github.com/candid82/joker/issues/452.
But I suspect this merely hides a bug somewhere...?
=> Stop crashing for now

all-tests.sh, build-all.sh
Could you attach BSD executables to future releases? This PR updates `build-all.sh` to build them.
=> Build executables for Free/Net/OpenBSD
